"""Local-ChroViewer 打包脚本:PyInstaller 单 exe(webview 本地窗口)。

输出:GitHub_Build/v<version>/
    Local-ChroViewer-v<version>/         运行目录(双击 Local-ChroViewer.exe)
    Local-ChroViewer-v<version>.zip      Release 发布用压缩包

用法:
    python scripts/build.py                    # 全量打包
    python scripts/build.py --skip-frontend    # 跳过前端产物检查
    python scripts/build.py --version 1.0.0    # 指定版本(默认 1.0.0)
"""
from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import zipfile

PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB_DIR = PROJECT_ROOT / "web"
DIST_DIR_DEFAULT = PROJECT_ROOT / "web" / ".output" / "public"
GITHUB_BUILD = PROJECT_ROOT / "GitHub_Build"
VERSION = "1.0.0"

ENTRY = str(PROJECT_ROOT / "launcher" / "entry_webview.py")
NAME = "Local-ChroViewer"


def ensure_frontend(rebuild: bool) -> bool:
    """前端产物检查;缺失或 --rebuild 时执行 pnpm 构建。"""
    index = DIST_DIR_DEFAULT / "index.html"
    if index.is_file() and not rebuild:
        print(f"[build] frontend dist ready: {DIST_DIR_DEFAULT}")
        return True
    print("[build] building frontend (pnpm exec vp build)...", flush=True)
    result = subprocess.run(["pnpm", "exec", "vp", "build"], cwd=str(WEB_DIR), shell=True)
    if result.returncode != 0:
        print("[build] frontend build FAILED", file=sys.stderr)
        return False
    return index.is_file()


def make_spec(version: str) -> pathlib.Path:
    """生成 PyInstaller spec(onedir, windowed, console=False)。"""
    spec_path = PROJECT_ROOT / "scripts" / f"{NAME}.spec"
    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by scripts/build.py (Local-ChroViewer v{version})
import pathlib

from PyInstaller.building.datastruct import Tree

ROOT = pathlib.Path(r"{PROJECT_ROOT}")

frontend_tree = Tree(str(ROOT / "web" / ".output" / "public"), prefix="frontend")

a = Analysis(
    [r"{ENTRY}"],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / "LICENSE"), "."),
        (str(ROOT / "README.md"), "."),
    ],
    hiddenimports=[
        "webview",
        "webview.platforms.winforms",
        "clr",
        "clr_loader",
        "uvicorn.logging",
        "uvicorn.loops.auto",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan.on",
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=["pytest", "tkinter", "unittest", "PIL"],
    noarchive=False,
)
a.datas += frontend_tree

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="{NAME}",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # windowed:不弹命令行窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "icon.ico"),   # ChroViewer 官方 logo
    contents_directory=".",
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="{NAME}",
    contents_directory=".",
)
"""
    spec_path.write_text(spec, encoding="utf-8")
    return spec_path


def make_zip(folder: pathlib.Path, zip_path: pathlib.Path) -> None:
    """把发布目录压缩为 zip(顶层为文件夹名)。"""
    print(f"[build] zipping -> {zip_path}", flush=True)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for file in sorted(folder.rglob("*")):
            if file.is_file():
                zf.write(file, file.relative_to(folder.parent).as_posix())
    print(f"[build] zip done: {zip_path} "
          f"({zip_path.stat().st_size / 1024 / 1024:.1f} MB)", flush=True)


def rm_rf(path: pathlib.Path) -> None:
    """删除目录;Windows 下文件被占用时重试并给出提示。"""
    for attempt in range(3):
        try:
            if path.exists():
                shutil.rmtree(path)
            return
        except PermissionError:
            if attempt < 2:
                time.sleep(1)
            else:
                print(f"[build] WARNING: cannot remove {path} (file in use?)", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description="Local-ChroViewer build script")
    parser.add_argument("--version", default=VERSION, help="版本号(默认 1.0.0)")
    parser.add_argument("--skip-frontend", action="store_true", help="跳过前端产物检查")
    parser.add_argument("--rebuild-frontend", action="store_true", help="强制重建前端")
    args = parser.parse_args()
    version = args.version

    if not args.skip_frontend and not ensure_frontend(args.rebuild_frontend):
        return 1

    import PyInstaller.__main__  # noqa: F401
    import time

    version_dir = GITHUB_BUILD / f"v{version}"
    final_dir = version_dir / f"{NAME}-v{version}"
    work_dir = GITHUB_BUILD / f".work-{NAME}"
    rm_rf(final_dir)
    rm_rf(work_dir)
    version_dir.mkdir(parents=True, exist_ok=True)

    print(f"[build] packaging {NAME} (webview window)", flush=True)
    spec_path = make_spec(version)
    PyInstaller.__main__.run([
        str(spec_path),
        "--clean",
        "--noconfirm",
        "--distpath", str(version_dir),
        "--workpath", str(work_dir),
    ])

    built = version_dir / NAME
    if not built.exists():
        print(f"[build] FAILED: {built} missing", file=sys.stderr)
        return 1
    built.rename(final_dir)
    print(f"[build] package -> {final_dir}", flush=True)

    # 版本说明
    (final_dir / "VERSION.txt").write_text(
        f"Local-ChroViewer v{version}\nGPL-2.0-only\n\n"
        "双击 Local-ChroViewer.exe 启动本地窗口\n",
        encoding="utf-8",
    )

    # Release 压缩包
    zip_path = version_dir / f"{NAME}-v{version}.zip"
    zip_path.unlink(missing_ok=True)
    make_zip(final_dir, zip_path)

    # 清理工作目录
    rm_rf(work_dir)
    rm_rf(version_dir / ".stage")

    print(f"[build] ALL DONE -> {version_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
