# -*- mode: python ; coding: utf-8 -*-
# Generated by scripts/build.py (Local-ChroViewer v1.0.0)
import pathlib

from PyInstaller.building.datastruct import Tree

ROOT = pathlib.Path(r"C:\Users\ZiRCON\Desktop\Local-ChroViewer")

frontend_tree = Tree(str(ROOT / "web" / ".output" / "public"), prefix="frontend")

a = Analysis(
    [r"C:\Users\ZiRCON\Desktop\Local-ChroViewer\launcher\entry_webview.py"],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / "LICENSE"), "."),
        (str(ROOT / "README.md"), "."),
    ],
    hiddenimports=[
        "webview",
        "webview.platforms.winforms",
        "clr",
        "clr_loader",
        "uvicorn.logging",
        "uvicorn.loops.auto",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan.on",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["pytest", "tkinter", "unittest", "PIL"],
    noarchive=False,
)
a.datas += frontend_tree

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Local-ChroViewer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # windowed:不弹命令行窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "assets" / "icon.ico"),   # ChroViewer 官方 logo
    contents_directory=".",
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Local-ChroViewer",
    contents_directory=".",
)
