/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiSourceRouteImport } from './routes/api/source'
import { Route as ApiPreviewMapRouteImport } from './routes/api/preview.map'
import { Route as ApiPreviewPartyRouteImport } from './routes/api/preview.party'
import { Route as ApiPreviewReplayRouteImport } from './routes/api/preview.replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewMapRoute = ApiPreviewMapRouteImport.update({
  id: '/api/preview/map',
  path: '/api/preview/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewPartyRoute = ApiPreviewPartyRouteImport.update({
  id: '/api/preview/party',
  path: '/api/preview/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewReplayRoute = ApiPreviewReplayRouteImport.update({
  id: '/api/preview/replay',
  path: '/api/preview/replay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/source': typeof ApiSourceRoute
  '/api/preview/map': typeof ApiPreviewMapRoute
  '/api/preview/party': typeof ApiPreviewPartyRoute
  '/api/preview/replay': typeof ApiPreviewReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/source': typeof ApiSourceRoute
  '/api/preview/map': typeof ApiPreviewMapRoute
  '/api/preview/party': typeof ApiPreviewPartyRoute
  '/api/preview/replay': typeof ApiPreviewReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/source': typeof ApiSourceRoute
  '/api/preview/map': typeof ApiPreviewMapRoute
  '/api/preview/party': typeof ApiPreviewPartyRoute
  '/api/preview/replay': typeof ApiPreviewReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/api/source'
    | '/api/preview/map'
    | '/api/preview/party'
    | '/api/preview/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/api/source'
    | '/api/preview/map'
    | '/api/preview/party'
    | '/api/preview/replay'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/api/source'
    | '/api/preview/map'
    | '/api/preview/party'
    | '/api/preview/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ApiSourceRoute: typeof ApiSourceRoute
  ApiPreviewMapRoute: typeof ApiPreviewMapRoute
  ApiPreviewPartyRoute: typeof ApiPreviewPartyRoute
  ApiPreviewReplayRoute: typeof ApiPreviewReplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/map': {
      id: '/api/preview/map'
      path: '/api/preview/map'
      fullPath: '/api/preview/map'
      preLoaderRoute: typeof ApiPreviewMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/party': {
      id: '/api/preview/party'
      path: '/api/preview/party'
      fullPath: '/api/preview/party'
      preLoaderRoute: typeof ApiPreviewPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview/replay': {
      id: '/api/preview/replay'
      path: '/api/preview/replay'
      fullPath: '/api/preview/replay'
      preLoaderRoute: typeof ApiPreviewReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ApiSourceRoute: ApiSourceRoute,
  ApiPreviewMapRoute: ApiPreviewMapRoute,
  ApiPreviewPartyRoute: ApiPreviewPartyRoute,
  ApiPreviewReplayRoute: ApiPreviewReplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
